CREATE SEQUENCE hibernate_sequence;

CREATE TABLE profile
(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    birthDay VARCHAR(100) NOT NULL ,
    email VARCHAR(100) NOT NULL UNIQUE ,
    username VARCHAR(100) UNIQUE NOT NULL ,
    password VARCHAR(100) UNIQUE NOT NULL
);